pipeline {
	    agent any 
	    stages {
	        stage('Build') {
	            steps {
	                echo 'Compilando codigo de mi aplicacion'
	            }
	        }
                stage('Testing'){
		  parallel {
			  stage('Test on windows'){
				  steps{
					sh '''
					  bash scripts/helloworld.sh
					'''
				  }
			  }
			  stage('Test on IOS'){
				  steps{
					sh '''
					  bash scripts/helloworld.sh
					'''
				  }
			  }
		  }
	        }
		stage('Deploy production') {
	            steps {
	                input message: "deploy en producion?"
	                echo 'deploy'
	            	}
	            }
 	 }
}
