pipeline {
	    agent none 
	    stages {
	        stage('Build') {
	            steps {
	                echo 'Compilando codigo de mi aplicacion'
	            }
	        }
	        stage('Test') {
		 parallel {
		    stage('test en windows'){
	              steps {
	                sh'''
			bash ./scripts/helloworld.sh
			'''
	              }
		    }
		    stage('test en linux'){
                      steps {
                        sh'''
                        bash ./scripts/helloworld.sh
                        '''
                      }
                    }
	        }
	     }
             stage('Deploy production') {
	            steps {
	                input message: "deploy en producion?"
	                echo 'deploy'
	            }
	        }
	 }
}
