apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: hello
labels:
  app: hello
spec:
strategy:
  type: Recreate
template:
  metadata:
    labels:
      app: hello
      tier: hello
  spec:
    containers:
    - name: hello
      image: isx46410800/hello:latest
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
        name: hello

---
apiVersion: v1
kind: Service
metadata:
name: hello
labels:
  app: hello
spec:
ports:
  - port: 5000
    targetPort: 5000
selector:
  app: hello
  tier: hello
type: LoadBalancer
