pipeline {
  agent any
  stages {
      stage('Comprobar repositorio git'){
          steps{
            git poll: true, url: 'https://github.com/isx46410800/M14_Jenkins.git'
          }
      }
      stage('Construimos imagen docker'){
          parallel {
              stage('Build On Windows') {
                        agent {
                            label "windows"
                        }
                        steps {
                            sh '''
								docker build -t isx46410800/appflask:windows app_parallel/.
							'''
                        }
              }
               stage('Build On IOS') {
                        agent {
                            label "IOS"
                        }
                        steps {
                            sh '''
								docker build -t isx46410800/appflask:ios app_parallel/.
							'''
                        }
              }
              stage('Build On Linux') {
                        agent {
                            label "linux"
                        }
                        steps {
                            sh '''
								docker build -t isx46410800/appflask:linux app_parallel/.
							'''
                        }
              }
          }
      }
      stage('Deploy app en docker'){
          parallel {
              stage('Test On Windows') {
                        agent {
                            label "windows"
                        }
                        steps {
                            sh '''
								docker run --rm --name appflask_win -h appflask_win -d isx46410800/appflask:windows
							'''
                        }
              }
               stage('Test On IOS') {
                        agent {
                            label "IOS"
                        }
                        steps {
                            sh '''
								docker run --rm --name appflask_ios -h appflask_ios -d isx46410800/appflask:ios
							'''
                        }
              }
              stage('Test On Linux') {
                        agent {
                            label "linux"
                        }
                        steps {
                            sh '''
								docker run --rm --name appflask_linux -h appflask_linux -d isx46410800/appflask:linux
							'''
                        }
              }
          }
      }
   }
}

